---
- name: nginx_config
  template: src=hello_world.conf.j2 dest=/etc/nginx/sites-available/default
- name: html_hello_world
  file:
    path: "{{ html_dir }}/hello_world"
    state: directory
    owner: "{{ html_owner }}"
    group: "{{ html_owner }}"
    mode: "{{ html_perms }}"

- name: hello_world
  copy:
    src: "files/html/hello_world/"
    dest: "{{ html_dir }}/hello_world"
    owner: "{{ html_owner }}"
    group: "{{ html_owner }}"
    mode: "{{ html_perms }}"
