# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "aspyatkin/ubuntu-18.04-server"
  config.vm.define "default"
  config.ssh.forward_agent = true

  config.vm.network "forwarded_port", guest: 80, host: 4080
  config.vm.network "forwarded_port", guest: 443, host: 4443

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
 end

  config.vm.provision "ansible-installer", type: "shell" do |init|
    init.path = "vagrant-ansible-installer.sh"
    run = "once"
  end

  #config.vm.provision "gitconfig", type: "shell", 
  #  inline: "echo -e '#{File.read("#{Dir.home}/.gitconfig")}' > '/home/vagrant/.gitconfig'"

  config.vm.provision "ansible", type: "ansible" do |ansible|
    #ansible.inventory_path = "../ansible/environments/dev"
    ansible.playbook = "../ansible/playbook.yml"
    #ansible.verbose = "vvv"
    #ansible.playbook = "../ansible/test.yml"
    run = "always"
  end

end
