kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
spec:
  type: LoadBalancer
  selector:
    app: nginx-helloworld
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: c3w-nginx-helloworld
spec:
  selector:
    matchLabels:
      app: nginx-helloworld
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-helloworld
    spec:
      containers:
      - name: nginx-helloworld
        image: c3w/nginx-helloworld:0.4
        ports:
        - containerPort: 80
#        volumeMounts:
#        - mountPath: "/var/www/html"
#          name: html
#      volumes:
#      - name: html
#        persistentVolumeClaim:
#          claimName: task-pv-claim
