kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volum2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "html/"
